Repository SineshX/PrabhawatiVidyaPeeth, pull requests merged in 2022-10, with the labels that each got.

#10 navbar changed
  index.html
  style.css
Labels: Hacktoberfest, navbar

#11 Navbar enhancements
  index.html
  style.css
Labels: Hacktoberfest, navbar

#38 Navbar hover animation change
  index.html
  style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#42 Fixed Text Size
  index.html
  style.css
Labels: hacktoberfest-accepted

#45 Feedback form added.Position change required for form
  feedback.js
  index.html
  style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#44 Preloader Added
  images/preloader.gif
  index.html
  style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#33 Adding Error 404 Pages Design
  images/Error 404 Page - Desktop version.png
  images/Error 404 Page - Mobile Version.png
Labels: Hacktoberfest, hacktoberfest-accepted

#46 Navbar Takes to respective section
  index.html
Labels: Hacktoberfest, hacktoberfest-accepted

#39 navbar update
  style.css
Labels: Hacktoberfest, hacktoberfest-accepted

#49 README Improvization
  README.md
Labels: Hacktoberfest, hacktoberfest-accepted
